name: Trigger auto deployment for pa200jkca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/pa200jkca-AutoDeployTrigger-c7b3fe3b-37e1-4853-833f-6f1ed136e786.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PA200JKCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PA200JKCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PA200JKCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: pa200jk.azurecr.io
          registryUsername: ${{ secrets.PA200JKCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PA200JKCA_REGISTRY_PASSWORD }}
          containerAppName: pa200jkca
          resourceGroup: PA200JKRG
          imageToBuild: pa200jk.azurecr.io/pa200jkca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


